# Generated by Django 3.2.6 on 2025-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='avisar_restock',
            field=models.BooleanField(default=False),
        ),
    ]
