# Generated by Django 3.2.6 on 2025-01-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_campana_motivo_bajacampana'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='avisar_restock',
            field=models.BooleanField(default=False),
        ),
    ]
