# Generated by Django 3.2.6 on 2025-01-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_producto_avisar_restock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='fecha_bajaSocio',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='motivo_bajaSocio',
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacSocio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
